import React, {useEffect, useState} from 'react';
import Head from "next/head";
import axios from "axios";
import {toast} from "react-toastify";
import Loader from "@/components/Loader";
import {useToken} from "@/contexts/JWTContext";
import {useRouter} from "next/router";
import {useUser} from "@/contexts/UserContext";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import {useTranslation} from "next-i18next";

function New(props) {

    const {jwt} = useToken();

    const router = useRouter();
    const {locale} = router

    const {user} = useUser();

    const {t} = useTranslation("common")

    const [code, setCode] = useState("")
    const [percentage, setPercentage] = useState(null)
    const [startsAt, setStartsAt] = useState("")
    const [endsAt, setEndsAt] = useState("")

    const [loader, setLoader] = useState(false);

    useEffect(() => {

        console.log("user: ", user)

        setLoader(true)
        let timeID;

        if(Object.keys(user).length > 0){
            if (!user?.roles?.includes("ROLE_ADMIN")){
                router.replace("/404", "/404", {locale}).then(() => setLoader(false))
            }
            else setLoader(false)
        }else {
            setLoader(true)
            timeID = setTimeout(() => router.replace("/404", "/404", {locale}), 1000*30)
        }

        return () => clearTimeout(timeID)

    }, [user.username])

    const handleSubmit = (e) => {
        e.preventDefault()

        setLoader(true);
        let timeID;

        const couponDetails = !startsAt || !endsAt ? {code, percentage} : {code, percentage, startsAt, endsAt}

        axios.post(
            '/api/coupon/new',
            {couponDetails, jwt},
            {headers: {}, withCredentials: true})
            .then(r => {
                toast.success(r.data.message, {
                    position: "top-center",
                    autoClose: 5000,
                    hideProgressBar: false,
                    closeOnClick: true,
                    pauseOnHover: true,
                    draggable: true,
                    progress: undefined,
                    theme: "dark",
                })
                router.push('/tsukingo/coupons','/tsukingo/coupons',{locale}).then(() => setLoader(false))
            })
            .catch(e => {
                timeID = setTimeout(() => {
                    toast.error(e.message, {
                        position: "top-center",
                        autoClose: 5000,
                        hideProgressBar: false,
                        closeOnClick: true,
                        pauseOnHover: true,
                        draggable: true,
                        progress: undefined,
                        theme: "dark",
                    })
                    router.push('/tsukingo/coupons','/tsukingo/coupons',{locale}).then(() => setLoader(false))
                }, 60000)
            })

        return () => clearTimeout(timeID)
    }

    return (
        <>
            <Head>
                <title>{user?.roles?.includes("ROLE_ADMIN") ? "HerboLAB : New Coupon" : "HerboLAB"}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="pt-12 lg:pt-24">
                {
                    loader
                        ?
                        <Loader/>
                        :
                        user.roles?.includes("ROLE_ADMIN")
                        &&
                        <div className="px-6 lg:px-8">
                            <h3 className="mb-4 text-xl font-medium text-gray-900 dark:text-white">{t('spark_interest_coupons')}</h3>
                            <form className="space-y-6" action="#" onSubmit={handleSubmit}>
                                <div>
                                    <label htmlFor="code" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{t('coupon_code')}</label>
                                    <input onChange={(e) => setCode(e.target.value)} defaultValue={code} type="text" name="code" id={`code`} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="asBnsGpdpd96" required={true}/>
                                </div>
                                <div>
                                    <label htmlFor="percentage" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{t('coupon_percentage')}</label>
                                    <input onChange={(e) => setPercentage(parseFloat(e.target.value))} defaultValue={percentage} type="text" name="percentage" id={`percentage`} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="15.5%" required={true}/>
                                </div>
                                <div>
                                    <label htmlFor="startsAt" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{t('begins_optional')}</label>
                                    <input onChange={(e) => setStartsAt(e.target.value)} defaultValue={startsAt} step={1} type="datetime-local" name="startsAt" id={`startsAt`} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="e.g : Aloe vera..." required={false}/>
                                </div>
                                <div>
                                    <label htmlFor="endsAt" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{t('ends_optional')}</label>
                                    <input onChange={(e) => setEndsAt(e.target.value)} defaultValue={endsAt} step={1} type="datetime-local" name="endsAt" id={`endsAt`} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="e.g : Aloe vera..." required={false}/>
                                </div>
                                <button type="submit" className="w-full text-white bg-teal-800 effect hover:bg-grn focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">{t('done_button')}</button>
                            </form>
                        </div>
                }
            </main>
        </>
    );
}

export async function getStaticProps({ locale }) {

    console.log("getStaticProps locale : ", locale)
    const fs = require('fs');

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"]))
        },
    };
}

export default New;