import React, {useEffect, useState} from 'react';
import Head from "next/head";
import {BiDotsVerticalRounded} from "react-icons/bi";
import EditModal from "@/components/EditModal";
import DeleteModal from "@/components/DeleteModal";
import axios from "axios";
import Loader from "@/components/Loader";
import {useToken} from "@/contexts/JWTContext";
import {useRouter} from "next/router";
import {useUser} from "@/contexts/UserContext";
import {useTranslation} from "next-i18next";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";

function Stocks(props) {

    const [showModals, setShowModals] = useState(false);
    const [stocks, setStocks] = useState([]);
    const [stockId, setStockId] = useState(null);
    const [loader, setLoader] = useState(false);

    const {jwt} = useToken();

    const {t} = useTranslation("common")

    const router = useRouter();
    const {user} = useUser();

    const {locale} = router

    useEffect(() => {

        setLoader(true);

        if(Object.keys(user).length > 0){
            axios.get('/api/stock/all',
                {
                    headers: {
                        Authorization: `Bearer ${jwt}`
                    },
                    withCredentials: true
                }
            )
                .then(r => {
                    setStocks(r.data)
                    setLoader(false)
                })
                .catch(e => {
                    console.log(e)
                })
        }

    }, [jwt])

    useEffect(() => {
        setLoader(true)
        let timeID;
        if(Object.keys(user).length > 0){
            if (!user?.roles?.includes("ROLE_ADMIN")){
                router.replace("/404", "/404", {locale}).then(() => setLoader(false))
            }
            else setLoader(false)
        }else {
            setLoader(true)
            timeID = setTimeout(() => router.replace("/404", "/404", {locale}), 1000*30)
        }

        return () => clearTimeout(timeID)

    }, [user.username])

    return (
        <>
            <Head>
                <title>{user?.roles?.includes("ROLE_ADMIN") ? "HerboLAB : Browse Stocks" : "HerboLAB"}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                loader
                    ?
                    <Loader/>
                    :
                    user.roles?.includes("ROLE_ADMIN")
                    &&
                    <main className="pt-12 lg:pt-24">
                        <button onClick={() => router.push("/tsukingo/stocks/new", "/tsukingo/stocks/new", {locale})} className="uppercase bg-ble text-white p-4 rounded-md mx-4 effect hover:bg-ble/80">
                            {t('new_stock_button')}
                        </button>
                        <div className="p-4">
                            <div className="w-full p-4 m-auto border rounded-lg bg-green-100 dark:bg-white/20 dark:border-black shadow-3xl overflow-y-auto">
                                <div className="my-3 p-3 effect grid grid-cols-2 md:grid-cols-12 sm:grid-cols-3 gap-[50px] sm:gap-[130px] md:gap-[150px] lg:gap-x-[275px] items-center justify-between cursor-pointer">
                                    <span className="uppercase">{t('stock_name')}</span>
                                    <span className="uppercase">{t('stock_quantity')}</span>
                                    <span className="uppercase hidden lg:grid">{t('id')}</span>
                                    <span className="uppercase hidden lg:grid">{t('details')}</span>
                                </div>
                                {
                                    loader
                                        ?
                                        <Loader/>
                                        :
                                        <ul>
                                            {
                                                stocks.map((stock, index) => {
                                                    const {id, name, quantity, product} = stock

                                                    return (
                                                        <li key={index} className="hover:shadow-3xl bg-green-50 hover:bg-white dark:bg-dark hover:bg-ble effect rounded-lg my-3 p-2 grid md:grid-cols-12 sm:grid-cols-3 gap-[50px] sm:gap-[130px] md:gap-[150px] lg:gap-x-[275px] justify-between cursor-pointer items-center">
                                                            <div className="flex items-center">
                                                                <div className="pl-4">
                                                                    <a href={`#`}>
                                                                        <p className="text-gray-700 dark:text-white flex">{name}</p>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                            <div className="text-white text-right sm:text-left flex items-center rounded-lg p-3 w-fit uppercase bg-ble">#{parseInt(quantity).toLocaleString()}</div>
                                                            <div className="text-gray-700 hidden dark:text-grn lg:flex">#{id}</div>
                                                            <button onClick={() => router.push(`/product/${product.id}`, `/product/${product.id}`, {locale})}>
                                                                <div className={`text-white text-right sm:text-left hidden lg:flex hover:underline items-center rounded-lg p-3 w-fit uppercase bg-teal-800`}>check corresponding product</div>
                                                            </button>
                                                            <div className="text-gray-700 dark:text-grn sm:flex justify-between items-center">
                                                                <div className="container2 space-x-1 w-full">
                                                                    <div className={`arrow-right bg-dark dark:bg-teal-500 relative p-5 rounded-lg flex flex-col justify-items-center space-y-4 ${showModals && stockId === id ? "visible" :"hidden"}`} id="modals">
                                                                        <EditModal context={"stock"} item={stock} stid={id} prodId={product.id}/>
                                                                        <DeleteModal context={"stock"} stid={id} prodId={product.id}/>
                                                                    </div>
                                                                    <button className="p-3" onClick={(e) => {
                                                                        e.preventDefault()
                                                                        e.stopPropagation()
                                                                        setShowModals(prev => !prev)
                                                                        setStockId(id)
                                                                    }}>
                                                                        <BiDotsVerticalRounded/>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    )
                                                })
                                            }
                                        </ul>
                                }
                            </div>
                        </div>
                    </main>
            }

        </>
    );
}

export async function getStaticProps({ locale }) {

    console.log("getStaticProps locale : ", locale)
    const fs = require('fs');

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"]))
        },
    };
}

export default Stocks;