import React, {useEffect, useState} from 'react';
import Head from "next/head";
import Loader from "@/components/Loader";
import Card from "@/components/Card";
import axios from "axios";
import {useRouter} from "next/router";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import Filter from "@/components/Filter";

function Products(props) {

    const [loader, setLoader] = useState(false);
    const [categories, setCategories] = useState([]);

    const router = useRouter();

    const {cid} = router.query

    const configData = {
        headers: {
            'Content-Type': 'application/json'
        }
    }

    useEffect(() => {

        setLoader(true);

        axios.get('/api/categories', configData)
            .then(r => {
                setCategories(r.data)
                setLoader(false)
            })
            .catch(e => {
                console.log(e.message)
            })

    }, [])

    const category = categories.find((c) => c.id === parseInt(cid))
    const products = []

    if(category)
    {
        for (const sub of category.subCategories) {
            for (const product of sub.products) {
                products.push(product)
            }
        }
    }

    console.log(category)

    return (
        <>
            <Head>
                <title>HerboLAB: {category?.name}'s Items</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="pt-16">
                {
                    loader
                        ?
                        <Loader/>
                        :
                        <Filter context="category" cid={cid}/>
                }
            </main>
        </>
    );
}

export async function getServerSideProps({ locale }) {

    console.log("getStaticProps locale : ", locale)
    const fs = require('fs');

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"]))
        },
    };
}

export default Products;