import React, {useEffect, useState} from 'react';
import {useRouter} from "next/router";
import axios from "axios";
import Loader from "@/components/Loader";
import Head from "next/head";
import Card from "@/components/Card";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import Filter from "@/components/Filter";

function sub(props) {

    const [loader, setLoader] = useState(false);
    const [products, setProducts] = useState([]);

    const router = useRouter();
    const {sid} = router.query;

    useEffect(() => {

        setLoader(true);

        if(sid){
            axios.get(`/api/sub-category/${sid}`)
                .then(r => {
                    setProducts(r.data);
                    setLoader(false);
                })
                .catch(e => {
                    console.log(e)
                })
        }

    }, [sid])

    return (
        <>
            <Head>
                <title>HerboLAB: Sub-Category {sid}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="pt-16">
                {
                    loader
                        ?
                        <Loader/>
                        :
                        <Filter context="sub-category" sid={sid}/>
                }
            </main>
        </>
    );
}

export async function getServerSideProps({ locale }) {

    console.log("getStaticProps locale : ", locale)
    const fs = require('fs');

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"]))
        },
    };
}

export default sub;