import React, {useEffect, useState} from 'react';
import Head from "next/head";
import Search from "@/components/Search";
import axios from "axios";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";

function SearchResults(props) {

    const [categories, setCategories] = useState([]);

    useEffect(() => {

        axios.get("/api/categories")
            .then(r => {
                setCategories(r.data)
            })
            .catch(e => {
                console.log(e.message)
            })
    }, []);

    return (
        <>
            <Head>
                <title>HerboLAB : Browse Search Results</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="pt-12 lg:pt-24">
                <Search categories={categories}/>
            </main>
        </>
    );
}

export async function getStaticProps({ locale }) {

    console.log("getStaticProps locale : ", locale)
    const fs = require('fs');

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"]))
        },
    };
}

export default SearchResults;