import Head from "next/head";
import Carousel from "@/components/Carousel";
import {useEffect, useState} from "react";
import axios from "axios";
import Loader from "@/components/Loader";
import ProductCarousel from "@/components/ProductCarousel"
import {useRouter} from "next/router";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import {useTranslation} from "next-i18next";

export default function Home() {

    const [banners, setBanners] = useState([]);
    const [products, setProducts] = useState([]);

    const [loader, setLoader] = useState(false);

    const configData = {
        headers: {
            'Content-Type': 'application/json'
        }
    }

    const router = useRouter();
    const { locale, locales } = router;

    const {t} = useTranslation("common")

    console.log("locale: ", locale)
    console.log("locales: ", locales)

    useEffect(() => {

        setLoader(true);

        axios.get('/api/product/products', configData)
            .then(r => {
                setProducts(r.data)
            })
            .catch(e => {
                console.log(e.message)
            })

        axios.get('/api/banners', configData)
            .then(r => {
                console.log(r.data)
                setBanners(r.data)
                setLoader(false)
            })
            .catch(e => {
                console.log(e.message)
            })
    }, [])

  return (
      <>
        <Head>
          <title>HerboLAB</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            {
                loader
                    ?
                    <Loader/>
                    :
                    <div className="container">
                        <Carousel bannersData={banners} context={"showcase"}/>
                    </div>
            }
            <div id="sections" className="mt-16 container space-y-11 bg-gray-100 dark:bg-white/5">
                <div>
                    <p className="text-3xl cursor-pointer text-org dark:text-white dark:hover:text-grn hover:text-ble effect">{t('newest_articles')}</p>
                    {products.length > 0 ? <ProductCarousel context={"newest"} items={products}/> : <Loader/>}
                </div>
                <div className="space-y-11">
                    <p className="text-3xl cursor-pointer text-org dark:text-white dark:hover:text-grn hover:text-ble effect">{t('best_offers')}</p>
                    {banners.length > 0 ? <Carousel context={"promo-and-into-sub"} bannersData={banners}/> : <Loader/>}
                    {products.length > 0 ? <ProductCarousel context={"on-promos"} items={products}/> : <Loader/>}
                </div>
                <div className="space-y-5">
                    <p className="text-3xl cursor-pointer text-org dark:text-white dark:hover:text-grn hover:text-ble effect">{t('categories')}</p>
                    <div id="pictures" className="flex-col lg:flex lg:flex-row justify-center flex-wrap justify-evenly space-y-7 lg:space-y-0">
                        <div onClick={() => router.push(`/home/category/${1}`, `/home/category/${1}`, {locale})}
                             className="space-y-4 flex flex-col items-center cursor-pointer">
                            <img className="w-32 h-32 hover:w-36 hover:h-36 effect rounded-full" src="/categories/cosmetics.png" alt="cosmetics"/>
                            <p className="text-center">{t('cosmetics')}</p>
                        </div>
                        <div onClick={() => router.push(`/home/category/${2}`, `/home/category/${2}`, {locale})}
                             className="space-y-4 flex flex-col items-center cursor-pointer">
                            <img className="w-32 h-32 hover:w-36 hover:h-36 effect rounded-full" src="/categories/food-supplements.png" alt="food-supplements"/>
                            <p className="text-center">{t('food_supplements')}</p>
                        </div>
                    </div>
                </div>
                <div>
                    <p className="text-3xl cursor-pointer text-org dark:text-white dark:hover:text-grn hover:text-ble effect">{t('popular_items')}</p>
                    {products.length > 0 ? <ProductCarousel context={"popular"} items={products}/> : <Loader/>}
                </div>
            </div>
        </main>
      </>
  )
}

export async function getStaticProps({ locale }) {

    console.log("getStaticProps locale : ", locale)
    const fs = require('fs');

    return {
        props: {
            ...(await serverSideTranslations(locale, ["common"]))
        },
    };
}